travis:
  secure:
    BINSTAR_TOKEN: cEkGL3MzWnNVunOyr1QR9oxuwv6lq+AZNG2JXqQC04jxn03eeRrMUxPOzaILQBMrPNTZEarth0GIOFhNmMj/ed7j9yzU2HCAH59gTJHEg5FMyEMUyHj8rEFuZ9uy0ii/B6LgwtVypVWhh1oNotrRvkWNcM/0vzIFmbobiVnmjmmMOOG064+2ARrdqaM6XVrvmdZ0w12m8T0KgTj7USC6ms9sf6wVcLuULjvJnNflLljAVETeLLO9EOnpLwxxzMaHidbeL8s7WTmRIoTfelXncMSq3zZYbuxaQJNaH8OIGDGpALx3FCL8f0RrRU04Mf++r8N/+ravv/RhLAEy/bNtVFXGjy+2pU0nMIrTBzeBXi1UQ3QCNeHDCFeCRg4hzmNf8NFmpifyl/awiquFwxKRQ5VsuPjQQRiYkNddbTUhxn73LaR74+FFaPYw9y7OW5xIJtkUfi3VdANPC/61kOyUNSHmG7r0YiFRI7W1oMVEOa4XhdbfpuQHODPLBZs/2gygMEY7BQZKYH/JAZ9kGR4gueDtbcEoB2ihqzBBeI3vgjgnqZIIAGBBeI62SMGXzFSjVmUhcqWwJKfST+yKK/BrD3WNj3qfBnnmwWSBTldr0KK4MaIJjugiTfincCvRmzgy51xIP2QA7VYNY34J6wHy+I/kkgVuzc2jA2RoFnom2mY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
